### PR TITLE
Support HTML in shortcode attributes

### PR DESCRIPTION
**Pull request by tsimons**
This changes the regex for detecting attributes with quotes to search past quotes that have a < in front of them. The only downside I can think of is that script tags could get past this, but I don't think this package is responsible for preventing XSS

### CODE REVIEW

**Comment by mblarsen** [comment]
Hi, thanks for the contribution. What would be the use case for this? 

I mean you can already do this:

```html
[code]
<a href='https://google.com'>a link</a>
[/code]
```

or for example:

```html
[code type="js"]
const a = 42
[/code]
```

Anything not recognized as tokens is returned as child text elements to that (open) token.

**Comment by tsimons** [comment]
We use WordPress as our headless CMS and gatsby for fetching data, building out a static site.

We have a shortcode called `[imgCaption]` It lets the author supply an image as the child of the shortcode, and a caption attribute that shows up near the image for accreditation and more info. What this ends up looking like is:

```
[imgCaption caption="Description of the image. Plus a <a href="...">link</a>"]
  <img src="..." alt="..." />
[/imgCaption]
```

This was supported by WordPress's shortcode parsing tool and has been utilized on hundreds of our blog posts already. Before this PR, I would get the invalid OPEN tag error and no shortcodes would be parsed at all. This fixed the issue for us

**Comment by mblarsen** [comment]
I'm not contesting the importance of this feature to you, but did you consider:

```
[imgCaption]
   [caption]Description of the image. Plus a <a href="...">link</a>[/caption]
  <img src="..." alt="..." />
[/imgCaption]
```

The AST you'll get will contain the caption as a tag token and img as a text token.

I'm hesitant to merge the commit at the moment primarily because of the implications paired with the small amount of rather naive tests added. 

When I have more time I'll look into it some more. 

PS: Have considered rewriting it to not use regexp

**Comment by tsimons** [comment]
Sorry if I came off as standoffish.

I was actually surprised when I saw that there was markup in our attributes and that Wordpress supported such a thing. I would definitely prefer the syntax you proposed, but I would have to update almost 1k posts with the new syntax. I'm totally cool leaving my version as a fork if you're uncomfortable merging this. We all know [HTML + regex = evil](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags).

**Comment by mblarsen** [comment]
Let's leave the PR open for now. Would there be a way to add your data as a separate HTML test suite? E.g. if the regexp could be used to correct your posts that would be a whole lot better.

Another option would be to let HTML match be opt-in. So when the instance is created https://github.com/mblarsen/shortcode-tokenizer/blob/master/src/shortcode-tokenizer.js#L230

You would specify: `html: true` it would require a little rearrangement of the regexp costs, but that is doable.

**Comment by tsimons** [comment]
I like the html flag. We could just indicate to use it at your own risk.

Once we ship the project, I can get all the posts that use this short code and built out that test suite. afaik, anchor tags are the only tags used.

**Comment by mblarsen** [comment]
See https://github.com/tsimons/shortcode-tokenizer/pull/1

**Comment by mblarsen** [comment]
@francoiscote @tsimons I see a bunch of different features being committed. Please commit separate PRs for those.

@tsimons did you have time to see the PR I made to your repo regarding HTML in params?

**Comment by francoiscote** [comment]
sorry about that, we accidentally polluted this PR. This branch became our working branch for dev work that we needed. We will probably have to open a new PR for this specific feature.

**Pull request closed without merging**
